Updated Mongodb package dependency (#488)
The existing code to add MongoDB's driver didn't work because of an extra name and incomplete version on the .product().

```
Error: Could not generate Xcode project: 'hello' /Users/mgomez/Developer/Swift/TrailBucket/hello: error: declared name 'FluentMongoDriver' for package dependency 'https://github.com/vapor/fluent-mongo-driver.git' does not match the actual package name 'fluent-mongo-driver'
```

```
error: because no versions of fluent-mongo-driver match the requirement 1.0.0..<2.0.0 and root depends on fluent-mongo-driver 1.0.0..<2.0.0, version solving failed.
```